spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/teste1
        username: postgres
        password: 12345678
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true

        
server:
    port: 3333

logging:
    level:
        org.springframework.security: DEBUG
        org.springframework.web: DEBUG