spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/camburiu_acessoria
        username: postgres
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    main:
        allow-circular-references: true

server:
    port: 8080